<?php

namespace Orca\MailBundle\Repository;

/**
 * MailTblMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailTblMailRepository extends \Doctrine\ORM\EntityRepository
{
}
