<?php

namespace Orca\MailBundle\Repository;

/**
 * MailTblVueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailTblVueRepository extends \Doctrine\ORM\EntityRepository
{
}
