<?php

namespace Orca\MailBundle\Repository;

/**
 * MailTblMailTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailTblMailTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
