<?php

namespace Orca\MailBundle\Repository;

/**
 * MailTblRegleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailTblRegleRepository extends \Doctrine\ORM\EntityRepository
{
}
