<?php

namespace Orca\MailBundle\Repository;

/**
 * MailTblRegleFrequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailTblRegleFrequenceRepository extends \Doctrine\ORM\EntityRepository
{
}
